# Generated by Django 2.2 on 2019-04-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_image/default-img.png', upload_to='profile_image'),
        ),
    ]
