# Generated by Django 2.2 on 2019-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_auto_20190412_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='static/userlogin/images/default-img.png', upload_to='profile_image'),
        ),
    ]
